replicaCount: 1

image:
  repository: docker-dev.artifactory.upcnet.es/so/aws-samples/sample-microservice-with-spinnaker
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: docker-dev

service:
  type: ClusterIP
  port: 8080
